import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { ApplicationLayout } from "./design/ApplicationLayout";
import { Content } from "./design/Content";
import { Header } from "./design/Header";
import { Sidebar } from "./design/Sidebar";
const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <div className = "h-screen w-screen flex  justify-center items-center">
        <ApplicationLayout>
          <Header>
            🎬 Cinetica
          </Header>
          <Sidebar></Sidebar>
          <Content>{children}</Content>
        </ApplicationLayout>
        </div>
  );
}
